#ifndef SUMOSUP_H
#define SUMOSUP_H
#include "types.h"

void initSumo();
void setLed(UInt8, UInt8);		
void clearLeds();
void checkIr();

#define IRL 1
#define IRR 2
UInt8	irOn(UInt8);
void initIr();

#define LED0 RD0
#define LED1 RD1
#define LED2 RD2
#define LED3 RD3
#define LED4 RD4

#define LEFT_MOTOR_ON	RC1=1;LED1=1
#define LEFT_MOTOR_OFF	RC1=0;LED1=0
#define RIGHT_MOTOR_ON	RC2=1;LED3=1
#define RIGHT_MOTOR_OFF	RC2=0;LED3=0

#define FORWARD	1
#define BACKWARD 0

#define LEFT_MOTOR_DIR	RC3
#define RIGHT_MOTOR_DIR	RC4

#define LEFT_MOTOR_FORWARD	LEFT_MOTOR_DIR=FORWARD;LED2=FORWARD
#define LEFT_MOTOR_BACKWARD	LEFT_MOTOR_DIR=BACKWARD;LED2=BACKWARD
#define RIGHT_MOTOR_FORWARD	RIGHT_MOTOR_DIR=FORWARD;LED4=FORWARD
#define RIGHT_MOTOR_BACKWARD RIGHT_MOTOR_DIR=BACKWARD;LED4=BACKWARD

#define SUMO_GO		LEFT_MOTOR_ON;RIGHT_MOTOR_ON
#define	SUMO_STOP	LEFT_MOTOR_OFF;RIGHT_MOTOR_OFF

#define SUMO_FORWARD \
	LEFT_MOTOR_FORWARD; \
	RIGHT_MOTOR_FORWARD; \
	SUMO_GO

#define SUMO_BACKWARD \
	LEFT_MOTOR_BACKWARD; \
	RIGHT_MOTOR_BACKWARD; \
	SUMO_GO

#define SUMO_ROTATE_LEFT \
	LEFT_MOTOR_BACKWARD \
	RIGHT_MOTOR_FORWARD \
	SUMO_GO

#define SUMO_ROTATE_RIGHT \
	RIGHT_MOTOR_BACKWARD \
	LEFT_MOTOR_FORWARD \
	SUMO_GO

#define IR_LEFT		RD5
#define IR_RIGHT	RD6



	
#endif
