; WARNING
; DO NOT EDIT THIS FILE 
; IT IS AUTOMATICALLY GENERATED BY A PERL SCRIPT
;
; Beginning of preamble file phrases.pre

	processor	16C73B
	#include	P16C73B.INC
	#include "timers.inc"
	#include "upstruct.inc"
#define	IN_PHRASES
	#include "phrases.inc"

RAM2	UDATA	
phraseptr	res	1
phrasenum	res	1
	global	phraseptr
	global	phrasenum



;
; End of preamble file phrases.pre
;

PROG1	CODE
getphrasecount
	global	getphrasecount
	retlw	8
JUMPS8	CODE
jumpphraselow
	global	jumpphraselow
	movlw	high jumpphraselow
	movwf	PCLATH
	movf	phrasenum,w
	addwf	PCL,f
	goto	phrase0low
	goto	phrase1low
	goto	phrase2low
	goto	phrase3low
	goto	phrase4low
	goto	phrase5low
	goto	phrase6low
	goto	phrase7low

jumpphrasehigh
	global	jumpphrasehigh
	movlw	high jumpphrasehigh
	movwf	PCLATH
	movf	phrasenum,w
	addwf	PCL,f
	goto	phrase0high
	goto	phrase1high
	goto	phrase2high
	goto	phrase3high
	goto	phrase4high
	goto	phrase5high
	goto	phrase6high
	goto	phrase7high

phrase0low
	movlw	high phrase0low
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(((7 & 0x7) << 5) |  ((((_C + D'12') + 1)) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  (((_C + D'12')) & 0x1f))
	retlw	eos

phrase0high
	movlw	high phrase0high
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(_nowait << 4 ) | _quart
	retlw	(_nowait << 4 ) | _8th
	retlw	0

phrase1low
	movlw	high phrase1low
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(((1 & 0x7) << 5) |  ((_E) & 0x1f))
	retlw	(((2 & 0x7) << 5) |  ((_F) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  (((_F + 1)) & 0x1f))
	retlw	(((7 & 0x7) << 5) |  ((_B) & 0x1f))
	retlw	(((5 & 0x7) << 5) |  (((_B - 1)) & 0x1f))
	retlw	eos

phrase1high
	movlw	high phrase1high
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _quart
	retlw	(_8th << 4 ) | _8th
	retlw	0

phrase2low
	movlw	high phrase2low
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(((1 & 0x7) << 5) |  ((_C) & 0x1f))
	retlw	(((2 & 0x7) << 5) |  ((_C) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  ((_C) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  (((_A + 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  ((_G) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  ((_F) & 0x1f))
	retlw	eos

phrase2high
	movlw	high phrase2high
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th
	retlw	(_nowait << 4 ) | _8th
	retlw	(_nowait << 4 ) | _quart
	retlw	(_nowait << 4 ) | _16th
	retlw	0

phrase3low
	movlw	high phrase3low
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(((4 & 0x7) << 5) |  ((_G) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  (((_B - 1)) & 0x1f))
	retlw	(((7 & 0x7) << 5) |  (((_C + D'12')) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  ((_B) & 0x1f))
	retlw	eos

phrase3high
	movlw	high phrase3high
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(_nowait << 4 ) | _8th3
	retlw	(_nowait << 4 ) | _8th3
	retlw	(_nowait << 4 ) | _8th3
	retlw	(_nowait << 4 ) | _quart
	retlw	(_nowait << 4 ) | _8th
	retlw	0

phrase4low
	movlw	high phrase4low
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(((5 & 0x7) << 5) |  ((_A) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  (((_A - 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  (((_E - 1)) & 0x1f))
	retlw	(((5 & 0x7) << 5) |  ((_A) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  (((_A - 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((5 & 0x7) << 5) |  ((_A) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  (((_A - 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  (((_E - 1)) & 0x1f))
	retlw	(((7 & 0x7) << 5) |  ((_C) & 0x1f))
	retlw	eos

phrase4high
	movlw	high phrase4high
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_8th << 4 ) | _8th
	retlw	0

phrase5low
	movlw	high phrase5low
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(((5 & 0x7) << 5) |  ((_C) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((5 & 0x7) << 5) |  ((_D) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((5 & 0x7) << 5) |  (((_E - 1)) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((5 & 0x7) << 5) |  ((_F) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  (((_F + 1)) & 0x1f))
	retlw	(((5 & 0x7) << 5) |  ((_G) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((5 & 0x7) << 5) |  ((_B) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((7 & 0x7) << 5) |  ((_B) & 0x1f))
	retlw	(((7 & 0x7) << 5) |  ((_choose) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  (((_C + 1)) & 0x1f))
	retlw	eos

phrase5high
	movlw	high phrase5high
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _quart
	retlw	(_nowait << 4 ) | _half
	retlw	0

phrase6low
	movlw	high phrase6low
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(((4 & 0x7) << 5) |  ((((_C + D'12') + 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  ((_C) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  ((((_C + D'12') + 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  ((_C) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  ((((_C + D'12') + 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  ((_C) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  ((((_C + D'12') + 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  (((_C + D'12')) & 0x1f))
	retlw	(((4 & 0x7) << 5) |  (((_C + 1)) & 0x1f))
	retlw	(((3 & 0x7) << 5) |  (((_C + D'12')) & 0x1f))
	retlw	(((2 & 0x7) << 5) |  ((_D) & 0x1f))
	retlw	eos

phrase6high
	movlw	high phrase6high
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _16th3
	retlw	(_nowait << 4 ) | _8th3
	retlw	0

phrase7low
	movlw	high phrase7low
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(((4 & 0x7) << 5) |  ((_G) & 0x1f))
	retlw	(((1 & 0x7) << 5) |  (((_A - 1)) & 0x1f))
	retlw	eos

phrase7high
	movlw	high phrase7high
	movwf	PCLATH
	movf	phraseptr,w
	addwf	PCL,f
	retlw	(_nowait << 4 ) | _half
	retlw	(_half << 4 ) | _half
	retlw	0


	END
